plugins: ["jest"]
env:
  es2021: true
  node: true
  jest/globals: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions: ["error", "ignorePackages", { "js": "always" }]
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-console: 0
root: true
